### PR TITLE
Fix "capitalize-acronyms" example

### PR DESCRIPTION
**Pull request by kkiermasz**
#### Summary

Fix "capitalize-acronyms" example

#### Reasoning

PR fixes the mistake I have made in #117 

_Please react with 👍/👎 if you agree or disagree with this proposal._

### CODE REVIEW

**Comment by kkiermasz** [comment]
Please wait until I rebase this branch

**Comment by kkiermasz** [comment]
Ready to go!

**Review by fdiaz — APPROVED** [review]
Thanks! And thanks to @bachand for catching this! Good eye 😉

**Comment by bachand** [comment]
Thanks for contributing @kkiermasz !

**Pull request merged**
