### PR TITLE
Sample change to cause lint failure in CI

### PR DESCRIPTION
**Pull request by calda**
This PR is a sample change that should cause the CI job to fail

### CODE REVIEW

**Comment by calda** [comment]
CI failed, nice!

**Comment by fdiaz** [comment]
Good stuff!

**Comment by bachand** [comment]
Nice! @calda do we feel confident we'll fail for rules validated by both SwiftFormat and SwiftLint?

**Comment by calda** [comment]
Yes! I tested both types of failures locally.

**Pull request closed without merging**
